services:
  mariadb:
    image: "mariadb"
    container_name: "mariadb"
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: "changeme"
      MYSQL_DATABASE: "dev_medzoner"
    ports:
      - "3306:3306"
    networks:
      - "default"
    volumes:
      - "mysql:/var/lib/mysql"

  mailhog:
    image: "mailhog/mailhog"
    container_name: "medzoner-mailhog"
#    hostname: "medzoner-mailhog"
    restart: "no"
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
    mysql:
        driver: local